service: aws-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-1

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-auto-swagger

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules:
      forceInclude:
        - pg
  autoswagger:
    title: 'Hot Wheels SHOP'
    apiType: 'http'
    basePath: '/dev'

functions:
  getProductsList:
    handler: './src/handlers/getProductsList.main'
    events:
      - http:
          path: products
          method: get
          cors: true
          swaggerTags: ['product service']
  getProductById:
    handler: './src/handlers/getProductById.main'
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
          swaggerTags: ['product service']
  createProduct:
    handler: './src/handlers/createProduct.main'
    events:
      - http:
          path: products
          method: post
          cors: true
          bodyType: 'CreateProduct'
          swaggerTags: [ 'product service' ]
